services:
  frontend:
    environment:
      - REACT_APP_API_URL=http://backend:5000
  db:
    command: ["postgres", "-c", "fsync=off", "-c", "full_page_writes=off"]
    tmpfs: /var/lib/postgresql
  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: "true"
    environment:
      - FLASK_ENV=testing
